# Generated by Django 5.2.4 on 2025-07-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestre',
            options={'ordering': ['carrera__nombre', 'nombre'], 'verbose_name': 'Semestre', 'verbose_name_plural': 'Semestres'},
        ),
        migrations.AlterField(
            model_name='semestre',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together={('nombre', 'carrera')},
        ),
    ]
