# Generated by Django 5.2.4 on 2025-08-02 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_alter_semestre_options_alter_semestre_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion_academica.estudiante')),
                ('materia_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='gestion_academica.materiasemestre')),
            ],
            options={
                'verbose_name': 'Inscripción de Estudiante',
                'verbose_name_plural': 'Inscripciones de Estudiantes',
                'unique_together': {('estudiante', 'materia_semestre')},
            },
        ),
    ]
