# Generated by Django 5.2.4 on 2025-08-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0003_inscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesionclase',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Sesión de Clase', 'verbose_name_plural': 'Sesiones de Clase'},
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='hora_fin',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='hora_inicio',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
