# Generated by Django 5.2.4 on 2025-08-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0004_alter_sesionclase_options_sesionclase_hora_fin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
