# Generated by Django 5.2.4 on 2025-08-04 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0005_delete_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.estudiante')),
                ('materia_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion_academica.materiasemestre')),
            ],
            options={
                'unique_together': {('estudiante', 'materia_semestre')},
            },
        ),
    ]
