# Generated by Django 5.2.4 on 2025-08-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0006_inscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={},
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='url_archivo',
        ),
        migrations.AddField(
            model_name='reporte',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
