# Generated by Django 5.2.5 on 2025-09-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0007_alter_reporte_options_remove_reporte_url_archivo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materiasemestre',
            unique_together={('materia', 'semestre', 'gestion', 'hora_inicio', 'hora_fin')},
        ),
        migrations.CreateModel(
            name='DiaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado'), ('SIN_CLASES', 'Día sin clases'), ('SUSPENSION', 'Suspensión de actividades')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('afecta_asistencia', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_especiales_creados', to='gestion_academica.administrador')),
            ],
            options={
                'verbose_name': 'Día Especial',
                'verbose_name_plural': 'Días Especiales',
                'ordering': ['-fecha'],
            },
        ),
    ]
